### ISSUE TITLE
Add documentation to run your partial work

### ISSUE THREAD

**Issue by h3ct0rjs** [librebeer/wtop#6]
Hi everybody, 
After checking the code I just notice  where the project goes, Is there any posibility to add a markdown file that explains how  to run or test the code?. 

Thanks in advance, 
PD: If it will look like [this](https://github.com/yaronn/blessed-contrib),it'll be pretty cool :smile:

**Comment by ivanchoff** [comment]
we are just talking about the final product, the main idea is do an npm package that tell you how much resource are taking you server, the question is ¿where show the info to user, in Term or in web Browser?. probably when we have a precise idea we will do a readme file.

**Comment by h3ct0rjs** [comment]
Cool @ivanchoff I do really like the Terminal option, is just more easy to run via ssh + tmux combination if you're not running a web server. How do you plan to implement the web option in case that your choice will be a web interface?.

**Comment by ivanchoff** [comment]
the problem with terminal option, is that when you run the app you can't see logs or user output data because it is occupied, (it is a problem that we need to solve!), in the case of web server, we think in use, socket and some fancy JS library for charts like d3, c3...(we need to decide which option!!)
